import { colors } from "@/constants/Colors";
import { Appearance, StyleSheet } from "react-native";

export const RoundStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  spinnerContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  roundRequestContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    columnGap: 20,
    rowGap: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    width: "100%",
    height: "100%",
  },
  roundContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    columnGap: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: colors.background.primary,
  },
  whenConatiner: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 2.5,
  },
  infoContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    textAlign: "left",
    rowGap: 10,
    flex: 1,
  },
  memberContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    columnGap: 5,
    rowGap: 5,
    flexWrap: "wrap",
  },
  attributeContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: 5,
    flexWrap: "wrap",
  },
  attribute: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    padding: 5,
  },
  scrollStyle: {
    width: "100%",
    backgroundColor: colors.background.secondary,
  },
  scrollStyleDetails: {
    width: "100%",
    backgroundColor: colors.background.primary,
  },
  roundScrollStyle: {
    gap: 5,
  },
  filterOverlayContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 10,
    right: 10,
    width: 50,
    height: 50,
    backgroundColor: colors.secondary.blue,
    borderRadius: 9999,
  },
  memberIconFilled: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9999,
    borderWidth: 2,
    height: 20,
    width: 20,
    borderColor: colors.primary.default,
    backgroundColor: colors.primary.default,
  },
  memberIconEmpty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9999,
    borderWidth: 2,
    height: 20,
    width: 20,
    borderColor: colors.neutral.medium,
    backgroundColor: colors.neutral.light,
  },
  roundDetailsContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    padding: 20,
    rowGap: 20,
  },
  roundDetails: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    rowGap: 5,
    width: "100%",
  },
  roundEditContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    padding: 20,
    rowGap: 20,
  },
  memberList: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    rowGap: 10,
    width: "100%",
  },
  memberListItem: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    columnGap: 20,
    height: 50,
    padding: 10,
    width: "100%",
    backgroundColor: colors.neutral.light,
    borderRadius: 10,
  },
  memberProfilePicture: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 9999,
    width: 40,
    height: 40,
  },
  memberListItemContent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    columnGap: 10,
  },
  actionButtonContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  hostIndicator: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 0,
    height: 0,
    borderRightWidth: 15, // Width of the left border
    borderTopWidth: 15, // Height of the bottom border
    borderRightColor: "transparent", // Left border color (transparent)
    borderTopColor: colors.primary.default, // Bottom border color (color of the triangle)
    borderStyle: "solid",
  },
  preferredAttribute: {
    backgroundColor: colors.primary.default,
    borderColor: colors.primary.default,
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderRadius: 4,
    borderWidth: 1,
  },
  indifferentAttribute: {
    backgroundColor: colors.neutral.medium,
    borderColor: colors.neutral.medium,
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderRadius: 4,
    borderWidth: 1,
  },
  dislikedAttribute: {
    backgroundColor: colors.alert.error,
    borderColor: colors.alert.error,
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderRadius: 4,
    borderWidth: 1,
  },
  buttonContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    columnGap: 10,
  },
  myRoundsButton: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    backgroundColor: colors.primary.default,
  },
  myRoundsButtonText: {
    color: colors.neutral.light,
  },
  textButtonContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    rowGap: 10,
  },
  notificationItemContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 5,
    backgroundColor: colors.background.primary,
  },
  notificationHeaderContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: colors.background.primary,
  },
  unreadDot: {
    width: 10,
    height: 10,
    borderRadius: 9999,
    backgroundColor: colors.primary.default,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.primary.dark,
    marginBottom: 10,
  },
  deleteButton: {
    backgroundColor: colors.alert.error,
    justifyContent: "center",
    height: "100%",
    width: 50,
    alignItems: "center",
  },
  notificationListContent: {
    backgroundColor: colors.background.secondary,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "100%",
  },
  badgeContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 0,
    right: 0,
  },
  hostBadge: {
    backgroundColor: colors.primary.default,
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 2.5,
  },
  memberBadge: {
    backgroundColor: colors.neutral.medium,
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 2.5,
  },
  memberBadgeText: {
    color:
      Appearance.getColorScheme() === "dark"
        ? colors.neutral.dark
        : colors.neutral.light,
  },
  distanceContainer: {
    position: "absolute",
    right: 0,
    bottom: 0,
  },
});
